"""Entity descriptions for the Daikin Onecta integration."""

from dataclasses import dataclass
from typing import Any

from homeassistant.components.binary_sensor import BinarySensorDeviceClass, BinarySensorEntityDescription
from homeassistant.components.climate import ClimateEntityDescription
from homeassistant.components.select import SelectEntityDescription
from homeassistant.components.sensor import CONF_STATE_CLASS, SensorDeviceClass, SensorEntityDescription, SensorStateClass
from homeassistant.components.switch import SwitchEntityDescription
from homeassistant.components.update import UpdateDeviceClass, UpdateEntityDescription
from homeassistant.const import (
    CONF_DEVICE_CLASS,
    CONF_ICON,
    CONF_UNIT_OF_MEASUREMENT,
    PERCENTAGE,
    REVOLUTIONS_PER_MINUTE,
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    UnitOfDensity,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
)
from homeassistant.helpers.entity import EntityCategory

ENABLED_DEFAULT = "Enabled"
STATE_CLASS = "STATE"
ENTITY_CATEGORY = "ENTITY_CATEGORY"
TRANSLATION_KEY = "TranslationKey"
MODEL_ATTRIBUTE = "ModelAttribute"


@dataclass(frozen=True, kw_only=True)
class DaikinSensorEntityDescription(SensorEntityDescription):
    """Describe a Daikin sensor and its source-model attribute."""

    model_attribute: str | None = None


# This maps the NAME as listed in the Daikin JSON data to:
# - DEVICE_CLASS: home assistant device class, see
#   https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes
# - UNIT_OF_MEASUREMENT:
# - ICON: Icon to be used
# - ENABLED_DEFAULT: Is the sensor enabled by default or not
# - TRANSLATION_KEY: Translation key
VALUE_SENSOR_MAPPING: dict[str, dict[str, Any]] = {
    "sgtin": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "sgtin",
    },
    "schedule": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:calendar-clock",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "schedule",
    },
    "controlMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:alphabetical",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "controlmode",
    },
    "onOffMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:toggle-switch-variant",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "onoffmode",
    },
    "operationMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:alphabetical",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "operationmode",
    },
    "airPurificationMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:alphabetical",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "airpurificationmode",
    },
    "setpointMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:alphabetical",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "setpointmode",
    },
    "heatupMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:alphabetical",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatupmode",
    },
    "wifiConnectionSSID": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:access-point-network",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "wificonnectionssid",
    },
    "wifiConnectionStrength": {
        CONF_DEVICE_CLASS: SensorDeviceClass.SIGNAL_STRENGTH,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
        CONF_ICON: "mdi:wifi",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "wificonnectionstrength",
    },
    "ssid": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:access-point-network",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "ssid",
    },
    "isHolidayModeActive": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isholidaymodeactive",
    },
    "isInErrorState": {
        CONF_DEVICE_CLASS: BinarySensorDeviceClass.PROBLEM,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isinerrorstate",
    },
    "isInWarningState": {
        CONF_DEVICE_CLASS: BinarySensorDeviceClass.PROBLEM,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isinwarningstate",
    },
    "isInInstallerState": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isininstallerstate",
    },
    "isInEmergencyState": {
        CONF_DEVICE_CLASS: BinarySensorDeviceClass.PROBLEM,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isinemergencystate",
    },
    "isPowerfulModeActive": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "ispowerfulmodeactive",
    },
    "isCoolHeatMaster": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "iscoolheatmaster",
    },
    "isInModeConflict": {
        CONF_DEVICE_CLASS: BinarySensorDeviceClass.PROBLEM,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isinmodeconflict",
    },
    "isInCautionState": {
        CONF_DEVICE_CLASS: BinarySensorDeviceClass.PROBLEM,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isincautionstate",
    },
    "isLockFunctionEnabled": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "islockfunctionenabled",
    },
    "ledEnabled": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "ledenabled",
    },
    "isFirmwareUpdateSupported": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "isfirmwareupdatesupported",
    },
    "daylightSavingTimeEnabled": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "daylightsavingtimeenabled",
    },
    "roomTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "roomtemperature",
        MODEL_ATTRIBUTE: "room_temperature",
    },
    "outdoorTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "outdoortemperature",
        MODEL_ATTRIBUTE: "outdoor_temperature",
    },
    "leavingWaterTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "leavingwatertemperature",
        MODEL_ATTRIBUTE: "leaving_water_temperature",
    },
    "leavingWaterOffset": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "leavingwateroffset",
    },
    "calculatedLeavingWaterTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "calculatedleavingwatertemperature",
    },
    "tankTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "mdi:bathtub-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "tanktemperature",
        MODEL_ATTRIBUTE: "tank_temperature",
    },
    "heatExchangerTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatexchangertemperature",
    },
    "suctionTemperature": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "suctiontemperature",
    },
    "deltaD": {
        CONF_DEVICE_CLASS: SensorDeviceClass.TEMPERATURE,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfTemperature.CELSIUS,
        CONF_ICON: "",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "deltad",
    },
    "dryKeepSetting": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:water-percent",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "drykeepsetting",
    },
    "streamerMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "hass:air-filter",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "streamermode",
    },
    "powerfulMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:rocket-launch",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "powerfulmode",
    },
    "econoMode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:leaf",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "economode",
    },
    "fanMotorRotationSpeed": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: REVOLUTIONS_PER_MINUTE,
        CONF_ICON: "mdi:fan",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "fanmotorrotationspeed",
    },
    "ipAddress": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:ip-network",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "ipaddress",
    },
    "dateTime": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "datetime",
    },
    "regionCode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "regioncode",
    },
    "errorCode": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "errorcode",
    },
    "timeZone": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "timezone",
    },
    "roomHumidity": {
        CONF_DEVICE_CLASS: SensorDeviceClass.HUMIDITY,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: PERCENTAGE,
        CONF_ICON: "mdi:water-percent",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "roomhumidity",
        MODEL_ATTRIBUTE: "room_humidity",
    },
    "pm1Concentration": {
        CONF_DEVICE_CLASS: SensorDeviceClass.PM1,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfDensity.MICROGRAMS_PER_CUBIC_METER,
        CONF_ICON: "mdi:blur",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "pm1concentration",
        MODEL_ATTRIBUTE: "pm1_concentration",
    },
    "pm25Concentration": {
        CONF_DEVICE_CLASS: SensorDeviceClass.PM25,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfDensity.MICROGRAMS_PER_CUBIC_METER,
        CONF_ICON: "mdi:blur",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "pm25concentration",
        MODEL_ATTRIBUTE: "pm25_concentration",
    },
    "pm10Concentration": {
        CONF_DEVICE_CLASS: SensorDeviceClass.PM10,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfDensity.MICROGRAMS_PER_CUBIC_METER,
        CONF_ICON: "mdi:blur",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "pm10concentration",
        MODEL_ATTRIBUTE: "pm10_concentration",
    },
    "CoolingDailyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingdailyelectricalconsumption",
    },
    "CoolingWeeklyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingweeklyelectricalconsumption",
    },
    "CoolingMonthlyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingmonthlyelectricalconsumption",
    },
    "CoolingYearlyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingyearlyelectricalconsumption",
    },
    "HeatingDailyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingdailyelectricalconsumption",
    },
    "HeatingWeeklyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingweeklyelectricalconsumption",
    },
    "HeatingMonthlyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingmonthlyelectricalconsumption",
    },
    "HeatingYearlyElectricalConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingyearlyelectricalconsumption",
    },
    "CoolingDailyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingdailygasconsumption",
    },
    "CoolingWeeklyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingweeklygasconsumption",
    },
    "CoolingMonthlyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingmonthlygasconsumption",
    },
    "CoolingYearlyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingyearlygasconsumption",
    },
    "HeatingDailyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingdailygasconsumption",
    },
    "HeatingWeeklyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingweeklygasconsumption",
    },
    "HeatingMonthlyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingmonthlygasconsumption",
    },
    "HeatingYearlyGasConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingyearlygasconsumption",
    },
    "RatelimitRemainingDay": {
        CONF_DEVICE_CLASS: None,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:information-outline",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "ratelimitremainingday",
    },
    "FirmwareUpdate": {
        CONF_DEVICE_CLASS: UpdateDeviceClass.FIRMWARE,
        CONF_STATE_CLASS: None,
        CONF_UNIT_OF_MEASUREMENT: None,
        CONF_ICON: "mdi:update",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: EntityCategory.DIAGNOSTIC,
        TRANSLATION_KEY: "firmwareupdate",
    },
    "currentPowerConsumption": {
        CONF_DEVICE_CLASS: SensorDeviceClass.POWER,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfPower.WATT,
        CONF_ICON: "mdi:lightning-bolt",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "currentpowerconsumption",
    },
    "currentHeatProduction": {
        CONF_DEVICE_CLASS: SensorDeviceClass.POWER,
        CONF_STATE_CLASS: SensorStateClass.MEASUREMENT,
        CONF_UNIT_OF_MEASUREMENT: UnitOfPower.WATT,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "currentthermaloutput",
    },
    "HeatingMonthlyThermalOutput": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingmonthlythermaloutput",
    },
    "HeatingYearlyThermalOutput": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:fire",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "heatingyearlythermaloutput",
    },
    "CoolingMonthlyThermalOutput": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingmonthlythermaloutput",
    },
    "CoolingYearlyThermalOutput": {
        CONF_DEVICE_CLASS: SensorDeviceClass.ENERGY,
        CONF_STATE_CLASS: SensorStateClass.TOTAL_INCREASING,
        CONF_UNIT_OF_MEASUREMENT: UnitOfEnergy.KILO_WATT_HOUR,
        CONF_ICON: "mdi:snowflake",
        ENABLED_DEFAULT: True,
        ENTITY_CATEGORY: None,
        TRANSLATION_KEY: "coolingyearlythermaloutput",
    },
}


def _entity_description_kwargs(metadata: dict[str, Any]) -> dict[str, Any]:
    """Return the entity-description fields shared by all platforms."""
    return {
        "icon": metadata[CONF_ICON],
        "translation_key": metadata[TRANSLATION_KEY],
        "entity_category": metadata[ENTITY_CATEGORY],
        "entity_registry_enabled_default": metadata[ENABLED_DEFAULT],
    }


SENSOR_DESCRIPTIONS = {
    value: DaikinSensorEntityDescription(
        key=value,
        device_class=metadata[CONF_DEVICE_CLASS],
        native_unit_of_measurement=metadata[CONF_UNIT_OF_MEASUREMENT],
        state_class=metadata[CONF_STATE_CLASS],
        model_attribute=metadata.get(MODEL_ATTRIBUTE),
        **_entity_description_kwargs(metadata),
    )
    for value, metadata in VALUE_SENSOR_MAPPING.items()
    if not isinstance(metadata[CONF_DEVICE_CLASS], BinarySensorDeviceClass) and not isinstance(metadata[CONF_DEVICE_CLASS], UpdateDeviceClass)
}

BINARY_SENSOR_DESCRIPTIONS = {
    value: BinarySensorEntityDescription(
        key=value,
        device_class=metadata[CONF_DEVICE_CLASS] if isinstance(metadata[CONF_DEVICE_CLASS], BinarySensorDeviceClass) else None,
        **_entity_description_kwargs(metadata),
    )
    for value, metadata in VALUE_SENSOR_MAPPING.items()
}

SWITCH_DESCRIPTIONS = {
    value: SwitchEntityDescription(key=value, **_entity_description_kwargs(metadata)) for value, metadata in VALUE_SENSOR_MAPPING.items()
}

SELECT_DESCRIPTIONS = {
    value: SelectEntityDescription(key=value, **_entity_description_kwargs(metadata)) for value, metadata in VALUE_SENSOR_MAPPING.items()
}

UPDATE_DESCRIPTIONS = {
    value: UpdateEntityDescription(
        key=value,
        device_class=metadata[CONF_DEVICE_CLASS],
        **_entity_description_kwargs(metadata),
    )
    for value, metadata in VALUE_SENSOR_MAPPING.items()
    if isinstance(metadata[CONF_DEVICE_CLASS], UpdateDeviceClass)
}

CLIMATE_DESCRIPTIONS: dict[str, ClimateEntityDescription] = {
    value: ClimateEntityDescription(key=value, translation_key=metadata[TRANSLATION_KEY]) for value, metadata in VALUE_SENSOR_MAPPING.items()
}
