name: Lokalise Translation Push

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - "custom_components/daikin_onecta/translations/en.json"
  repository_dispatch:
    types: [lokalise_webhook]
  workflow_dispatch:

jobs:
  push-source:
    permissions:
      contents: read
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Installeer Lokalise CLI v2 via curl
        run: |
          url="https://raw.githubusercontent.com"
          url+="/lokalise/lokalise-cli-2-go/master/install.sh"
          curl -sfL "$url" | sh
          sudo mv ./bin/lokalise2 /usr/local/bin/lokalise2

      - name: Push en.json naar Lokalise
        run: |
          lokalise2 file upload \
            --token "${{ secrets.LOKALISE_API_TOKEN }}" \
            --project-id "${{ secrets.LOKALISE_PROJECT_ID }}" \
            --file \
            "custom_components/daikin_onecta/translations/en.json" \
            --lang-iso "en" \
            --replace-modified
