name: Validate with prek

on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    runs-on: "ubuntu-slim"
    name: Prek
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install development tools
        run: |
          pip install --constraint=.github/workflows/constraints.txt \
            -r requirements_dev.txt
      - name: Run prek on all files
        run: |
          prek run --all-files --show-diff-on-failure --color=always
