name: HACS Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    permissions:
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        with:
          category: "integration"
